### ISSUE TITLE
Ikoner på knapper blir borte i IE11

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#1]
Espen har IE11 på maskinen. Der blir knappeikoner blir borte.

Er det noe @jorjoh greier å fikse?

![12633021_10156704491715112_113197939_o](https://cloud.githubusercontent.com/assets/701351/12733635/4428f362-c93c-11e5-9402-8f1b36a7460e.jpg)

**Comment by zrrrzzt** [comment]
ikoner på knapper blir borte i Tfk-utgaver av IE. Ser det skjer i Citrix og andre IE-utgaver installert på bruket.

Sjekket på browserstack og der er ikonene som de skal.

Tror du skal sjekke om Team IT har satt noen artige begrensninger et sted

**Comment by maccyber** [comment]
Får denne beskjeden i IE-konsollen:
HTML1202: https://test.minelev.t-fk.no/login kjøres i kompatibilitetsvisning fordi det er merket av for Vis intranettområder i kompatibilitetsvisning.

Ser ut som *.t-fk.no er lagt til i intranett listen.

**Comment by zrrrzzt** [comment]
noe slikt kan vel fort krølle til saker og ting ja

**Comment by jorjoh** [comment]
Hei hei, ordnet det seg med knappene?, jeg har vært veldig opptatt denne uken på grunn av høy pågang med bachelor oppgaven og møter med ekstern kontakt til oppgaven med klarering av hvordan alt skal se ut, så har ikke fått tid til å ta stilling til de ‘issuene’ dere la ut. Håper det løste seg :) 

Mvh. 

Jørgen Johansen 

Informasjonssystemer og IT-ledelse

Høgskolen i Sørøst-Norge

**Comment by zrrrzzt** [comment]
@jorjoh ikke noe feil i koden. Bare "feil" i internt regelsett og kompatibilitetsmode på MSIE
