### ISSUE TITLE
Tydeligere søkefelt

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#11]
Ønsker et tydeligere søkefelt. F.eks. annen farge?

**Comment by vavaen** [comment]
Jeg syns ikke annen farge.

Fra: Jonas Enge [mailto:notifications@github.com]
Sendt: 8. februar 2016 20:13
Til: telemark/minelev minelev@noreply.github.com
Emne: [minelev] Tydeligere søkefelt (#11)

Ønsker et tydeligere søkefelt. F.eks. annen farge?

**Comment by zrrrzzt** [comment]
Det nye søkefeltet (vet ikke om det er ute i noen versjoner nå) ble gjort tydligere ved å ha surt bunnlinje i stedet for lys grå. I tillegg ble den like tykk som den grønne streken som dukker opp når søkefeltet er aktivt
