### ISSUE TITLE
Får "Failed to load a plugin: yar  undefined" i loggen

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#14]
Ser ikke ut som yar blir lastet.
Får "Failed to load a plugin: yar  undefined" i loggen.

**Comment by zrrrzzt** [comment]
Yar lastes. undefined er faktisk console.log av error-objektet.

Nå brukes ikke Yar lenger etter at man henter enkeltelever fra buddy så yar kan fjernes fra MinElev
