### ISSUE TITLE
Logo Tfk 

### ISSUE THREAD

**Issue by vavaen** [telemark/minelev#16]
Jeg syns det var et godt forslag å få inn logoen vår (øksa). Jeg foreslår til høyre eller venstre for MinElev i det det gule feltet?

**Comment by zrrrzzt** [comment]
Da er du tildelt oppgaven med å skaffe den til veie i en form som kan brukes :-)

**Comment by vavaen** [comment]
https://rom.t-fk.no/informasjon/kommunikasjon/logo/SitePages/Hjemmeside.aspx

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 9. februar 2016 09:45
Til: telemark/minelev minelev@noreply.github.com
Kopi: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Logo Tfk (#16)

Da er du tildelt oppgaven med å skaffe den til veie i en form som kan brukes :-)

**Comment by zrrrzzt** [comment]
Den kan ikke brukes. Altfor stor.

Må finne noe her https://designguide.t-fk.no/ og skalere til rett str

**Comment by vavaen** [comment]
https://designguide.t-fk.no/media/1342/logo_telemark_fylkeskommune.jpg

Får du til å eskalere ned?

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 9. februar 2016 12:46
Til: telemark/minelev minelev@noreply.github.com
Kopi: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Logo Tfk (#16)

Den kan ikke brukes. Altfor stor.

Må finne noe her https://designguide.t-fk.no/ og skalere til rett str

**Comment by zrrrzzt** [comment]
vil helst få den ferdig, har knapt nok tid til å kode raskt nok nå

**Comment by vavaen** [comment]
Hvor liten skal den være?

-------- Opprinnelig melding --------
Fra: Geir Gåsodden notifications@github.com
Dato: 09.02.2016 15.39 (GMT+01:00)
Til: telemark/minelev minelev@noreply.github.com
Ko: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Logo Tfk (#16)

vil helst få den ferdig, har knapt nok tid til å kode raskt nok nå

##

**Comment by zrrrzzt** [comment]
@evasdrugg kan du se på en logo som passer for MinElev og samtidig er innenfor den grafiske profilen?

**Comment by evasdrugg** [comment]
https://designguide.t-fk.no/logo-og-bruk/hovedlogo/ <--- logopakke lastes ned her. Mtp størrelse ogsånn er ikke jeg riktig person å spørre... Lise Loktu er i hvert fall utdannet grafisk designer :)

**Comment by vavaen** [comment]
Geir: Jeg sjekker dette ut.
Eva Susanne: Takk for tips :)

-------- Opprinnelig melding --------
Fra: evasdrugg notifications@github.com
Dato: 09.02.2016 21.03 (GMT+01:00)
Til: telemark/minelev minelev@noreply.github.com
Ko: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Logo Tfk (#16)

https://designguide.t-fk.no/logo-og-bruk/hovedlogo/ <--- logopakke lastes ned her. Mtp st?rrelse ogs?nn er ikke jeg riktig person ? sp?rre... Lise Loktu er i hvert fall utdannet grafisk designer :)

##
