### ISSUE TITLE
Bilde av elever på framsiden

### ISSUE THREAD

**Issue by vavaen** [telemark/minelev#17]
Hva syns dere? Skal jeg ordne et? Fiktiv bilde eller av ordentlige mennesker?

**Comment by zrrrzzt** [comment]
Jeg synes vi skal holde oss utelukkende til hva som tilfører systemet funksjonalitet. Dette er et rent verktøy og bør fremstå uten "forvirrende" elementer.

**Comment by vavaen** [comment]
ok

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 9. februar 2016 09:46
Til: telemark/minelev minelev@noreply.github.com
Kopi: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Bilde av elever på framsiden (#17)

Jeg synes vi skal holde oss utelukkende til hva som tilfører systemet funksjonalitet. Dette er et rent verktøy og bør fremstå uten "forvirrende" elementer.
