### ISSUE TITLE
Halvårsvurdering 1. og 2. termin 

### ISSUE THREAD

**Issue by vavaen** [telemark/minelev#18]
Etter gårdagens rektormøte har jeg hatt en runde med Ben på dette med termin og halvårsvurdering. Det korrekte vi bør ha i skjema er

Halvårsvurdering 1.termin
Halvårsvurdering 2.termin
Standpunktkarakter

Dette er begreper etter opplæringsloven.

**Comment by zrrrzzt** [comment]
http://regbok.udir.no/35004/3344/35042-1014322.html H1, H2 og ST er kodene fra udir som også brukes av diverse systemer

Ta en ny runde med sjekker før vi endrer?

**Comment by vavaen** [comment]
Vi går for slik jeg definerte begrepene nedenfor, og ikke forkortelser.

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 18. februar 2016 15:57
Til: telemark/minelev minelev@noreply.github.com
Kopi: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Halvårsvurdering 1. og 2. termin (#18)

http://regbok.udir.no/35004/3344/35042-1014322.html H1, H2 og ST er kodene fra udir som også brukes av diverse systemer

Ta en ny runde med sjekker før vi endrer?
