### ISSUE TITLE
Hjelpetekst - søk

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#19]
Ser i loggen at brukere søker etter elever med hele navnet.
Noen ganger får de ikke treff, da de ikke har husket mellomnavnet.

Kan vi få frem enda tydligere at man bare trenger å søke etter deler av navnet?
Også i opplæringsvideoen.

**Comment by zrrrzzt** [comment]
Skal legge inn melding i teksten som dukker opp når man ikke får treff.

@Tmholen antar jeg fikser videoen

**Comment by vavaen** [comment]
Så flott du legger merke til sånt, Jonas ☺

Fra: Jonas Enge [mailto:notifications@github.com]
Sendt: 18. februar 2016 23:09
Til: telemark/minelev minelev@noreply.github.com
Emne: [minelev] Hjelpetekst - søk (#19)

Ser i loggen at brukere søker etter elever med hele navnet.
Noen ganger får de ikke treff, da de ikke har husket mellomnavnet.

Kan vi få frem enda tydligere at man bare trenger å søke etter deler av navnet?
Også i opplæringsvideoen.
