### ISSUE TITLE
Legge til status "Kan ikke sendes automatisk"

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#20]
Legge til status "Kan ikke sendes automatisk" på hjelpesiden

**Comment by zrrrzzt** [comment]
Tekstforslag fra @vavaen 

``` sh
Varselet stoppet opp i utsendingprosessen. Det kan være fordi eleven har hemmelig adresse, ikke har folkeregister adresse i Telemark eller andre feil. Varselet blir tatt hånd om manuelt og sendt ut pr post samt arkivet i 360.
```

Jeg foreslår en litt kortere variant:

``` sh
Varselet stoppet opp i utsendingprosessen. Det blir tatt hånd om manuelt og sendt ut pr post samt arkivert i 360.
```

Hva tenker dere @maccyber @vavaen ?

**Comment by vavaen** [comment]
Takk!
Mye bedre.
Gir du meg beskjed når det er endret på hjelpe-siden, for da kan jeg i svaret til læreren henvise til den.

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 4. mars 2016 04:35
Til: telemark/minelev minelev@noreply.github.com
Kopi: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Legge til status "Kan ikke sendes automatisk" (#20)

Tekstforslag fra @vavaenhttps://github.com/vavaen

Varselet stoppet opp i utsendingprosessen. Det kan være fordi eleven har hemmelig adresse, ikke har folkeregister adresse i Telemark eller andre feil. Varselet blir tatt hånd om manuelt og sendt ut pr post samt arkivet i 360.

Jeg foreslår en litt kortere variant:

Varselet stoppet opp i utsendingprosessen. Det blir tatt hånd om manuelt og sendt ut pr post samt arkivert i 360.

Hva tenker dere @maccyberhttps://github.com/maccyber @vavaenhttps://github.com/vavaen ?

**Comment by zrrrzzt** [comment]
Jupp @vavaen Skal du ha tilbakemeldingsfunksjonen også?

**Comment by vavaen** [comment]
Så klart!
Ja takk ☺

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 4. mars 2016 09:42
Til: telemark/minelev minelev@noreply.github.com
Kopi: Vanja Valjord Christensen Vanja.Valjord.Christensen@t-fk.no
Emne: Re: [minelev] Legge til status "Kan ikke sendes automatisk" (#20)

Jupp @vavaenhttps://github.com/vavaen Skal du ha tilbakemeldingsfunksjonen også?

**Comment by zrrrzzt** [comment]
Final tekst

```
Varselet stoppet opp i utsendingsprosessen. Det blir tatt hånd om manuelt, sendt ut og arkivert i 360.
```

**Comment by zrrrzzt** [comment]
fixed via https://github.com/telemark/roy/commit/d6c349511c4663f2252e7a1efa8fae50619ea4aa
