### ISSUE TITLE
Ikoner for iphone/android/windows10 osv

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#21]
Generering av ikoner til android, iphone, ipad, windows 10 osv kan gjøres på
http://realfavicongenerator.net/

Skulle vi hatt et eget ikon for "MinElev" eller bruke øksa?
![tfk](https://cloud.githubusercontent.com/assets/701351/13466275/8487eb88-e099-11e5-847a-629023bab826.png)

**Comment by zrrrzzt** [comment]
Dette bør ligge i designguiden @evasdrugg 

Kan du få bestilt slike i koner og lagt de inn der?

**Comment by zrrrzzt** [comment]
fant de offisielle i en mail @evasdrugg 

sender de til deg så du kan få de ut i designguiden

**Comment by evasdrugg** [comment]
Jippi! Hvor hen i designguide passer de...? Passer lissom ikke inn under noen av punktene? Kunne evt forandret logomenypunkt...

**Comment by zrrrzzt** [comment]
de bør finnes både under logo og web. Evt ligge et sted og pekes til det andre @evasdrugg
