### ISSUE TITLE
Legge statistikk i api

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#25]
Foreslår at vi legger logs-statistikk i api, f.eks. noe lignende

| api | query |
| --- | --- |
| /stats/schools | db.logs.aggregate( { $group : { _id : "$schoolName", total : { $sum : 1 }} }, { $sort: { total: -1 } } ) |
| /stats/total | db.logs.count() |
| /stats/failed | db.logs.find({ "documentStatus.status": "Kan ikke sendes automatisk" }).count() |

.. evt all-in-one
Kan vel ligge public?

**Comment by vavaen** [comment]
Kan ligge Public ja, hvis det kun er skole og tall.

Fra: Jonas Enge [mailto:notifications@github.com]
Sendt: 10. mars 2016 13:39
Til: telemark/minelev minelev@noreply.github.com
Emne: [minelev] Legge statistikk i api (#25)

Foreslår at vi legger logs-statistikk i api, f.eks. noe lignende
api

query

/stats/schools

db.logs.aggregate( { $group : { _id : "$schoolName", total : { $sum : 1 }} })

/stats/total

db.logs.count()

/stats/failed

db.logs.find({ "documentStatus.status": "Kan ikke sendes automatisk" }).count()

Kan vel ligge public?

**Comment by zrrrzzt** [comment]
Lagt inn følgende

`/stats/schools`Viser antall varsler pr skole

`/stats/total`Viser totalt antall varsler

`/stats/status`Viser antall pr status

Man må være innlogget for å se disse og enn så lenge er det kun json-visning av de dvs at det funker best om man f.eks. bruker Chrome og har installert [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en)

På sikt kan man utvide disse med pen visnig og f.eks, ulike filtere

Seff ikke aktivt ute før @maccyber har oppdatert :-)
