### ISSUE TITLE
Sortering av fag

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#5]
![asd](https://cloud.githubusercontent.com/assets/701351/12876143/e8736a66-cdfa-11e5-8fde-649f139c394e.jpg)

Skal vi sortere fag alfabetisk?
Tar du det eller skal jeg ta det i SQL-en?

**Comment by zrrrzzt** [comment]
Foreslår sql i  denne omgang. Har brukt opp avsatt tid på webgrensesnittet i denne omgang :-)
