### ISSUE TITLE
Forhåndsvisning fungerer ikke hvis endring - IE

### ISSUE THREAD

**Issue by maccyber** [telemark/minelev#8]
Forhåndsvisning første gang, fungerer.
Deretter kommer:
Gir "Objektet støtter ikke egenskapen eller metoden remove Linje 8 material-modal.min.js".

**Comment by zrrrzzt** [comment]
https://github.com/MarkRabey/material-modal/issues/1 får vente til det evt blir fikset i hovedbiblioteket
